### ISSUE TITLE
Fortran compiler not found

### ISSUE THREAD

**Issue by VAnavangot** [maia-sdr/pm-remez#2]
When I am installing the rust package using python build I am facing an error `FortranCompilerNotFound`. Is there any library requirement for installation of pm-remez?

**Comment by VAnavangot** [comment]
Hi @daniestevez, Thanks for your response

> What are you trying to do? Depending on that, one build method or another might make more sense for your use case.

I am trying to install pm-remez and use it in python. I first installed the the packages using `cargo build ...` -- this did not cause any errors if I am not wrong. But while installing the python package using `python -m build` I am facing the `FortranCompilerNotFound` error. 

> A Fortran compiler is definitely required if you compile a LAPACK implementation such as OpenBLAS as part of the build. I'm not sure if you also need a Fortran compiler if you link against a LAPACK library already available in the system.
> 
> What are you trying to do? Depending on that, one build method or another might make more sense for your use case.

**Comment by VAnavangot** [comment]
Installing `gfortran` could resolve this issue. 

Now `pm_remez` works from me in python :smile: . TY @daniestevez

**Comment by daniestevez** [comment]
There are binary packages published in PyPI for the most common architectures and operating systems, so probably you could have done `pip install pm-remez` instead of building from source. I see that this isn't mentioned in the README, so I'm updating it to include it in #3.
